### ISSUE TITLE
ellipsis is listed as an Import but isn't used

### ISSUE THREAD

**Issue by DavisVaughan** [malcolmbarrett/metaconfoundr#11]
```r
*   checking dependencies in R code ... NOTE
    ```
    Namespace in Imports field not imported from: ‘ellipsis’
      All declared Imports should be used.
    ```
```

Not entirely sure why this showed up as a revdep of dplyr (it isn't a problem, per se), but thought you might like to know

**Comment by malcolmbarrett** [comment]
Thanks! This turned out to be a bug in my tidyselect imports which I must have copy and pasted between these projects
