### ISSUE TITLE
Robins label

### ISSUE THREAD

**Issue by JulieMOPetersen** [malcolmbarrett/metaconfoundr#14]
When using the Robins labeling option, the legend shows low risk symbol (+) for both high and low risk studies 
![robins label](https://user-images.githubusercontent.com/51957341/194889480-3a310c5d-49d5-4e0d-b806-d97eed5219de.png)

mc_trafficlight(mc_ipi) +
  theme_mc() +
  geom_cochrane() + 
  scale_fill_cochrane(labels = label_robins())  +
  ggplot2::guides(x = ggplot2::guide_axis(n.dodge = 2))

**Comment by malcolmbarrett** [comment]
Both this and #13 should be fixed with an incoming patch

``` r
library(metaconfoundr)
mc_trafficlight(metaconfoundr(ipi)) +
  theme_mc() +
  geom_cochrane() +
  scale_fill_cochrane(labels = label_robins()) +
  scale_shape_cochrane(labels = label_robins()) +
  ggplot2::guides(x = ggplot2::guide_axis(n.dodge = 2))
#> Scale for shape is already present.
#> Adding another scale for shape, which will replace the existing scale.
```

![](https://i.imgur.com/9pAjxtb.png)

<sup>Created on 2022-12-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chloeeburke** [comment]
Hi @malcolmbarrett  - thanks for looking into this. Can I ask when the planned release of the incoming patch is? Currently trying to use this package in a current project. Thanks.

**Comment by malcolmbarrett** [comment]
You can install it right now from GitHub: 

```r
# if needed
# install.packages("remotes")
remotes::install_github("malcolmbarrett/metaconfoundr")
```

**Comment by JulieMOPetersen** [comment]
Thank you, Malcolm!!

**Comment by chloeeburke** [comment]
Fantastic - thank you!

**Comment by malcolmbarrett** [comment]
FYI this fix is on its way to CRAN, as well, so soon you can install with `install.packages()` to get this fix
